const productData = {
    tshirts: [
      { id: 1, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-1.jpg", name: "Black Tee with print.", price: "49.99" },
      { id: 2, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-2.jpg", name: "White Tee with print.", price: "49.99" },
      { id: 3, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-3.jpg", name: "White Tee with print.", price: "49.99" },
      { id: 4, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-4.jpg", name: "White Tee with print.", price: "49.99" },
      { id: 5, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-5.jpeg", name: "Purple Tee.", price: "49.99" },
      { id: 6, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-6.jpeg", name: "White Tee.", price: "49.99" },
      { id: 7, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-7.jpeg", name: "Black Tee.", price: "49.99" },
      { id: 8, description: "Elevate your everyday look with the StreetCanvas Tee - a wardrobe essential for the urban trendsetter. Crafted from premium cotton for unparalleled comfort, this tee features a minimalist yet impactful design, making it the perfect canvas for your street style expression.", image: "/assets/tshirts/tshirt-8.jpeg", name: "White Tee.", price: "49.99" },
    ],
    hoodies: [
      { id: 9, description: "Introducing the CityFlex Hoodie, where cutting-edge technology meets streetwear flair. This hoodie boasts a tech-inspired design with hidden pockets for your gadgets, making it the ultimate fusion of style and functionality.", image: "/assets/hoodies/hoodie-1.jpeg", name: "Cream Hoodie.", price: "49.99" },
      { id: 10, description: "Introducing the CityFlex Hoodie, where cutting-edge technology meets streetwear flair. This hoodie boasts a tech-inspired design with hidden pockets for your gadgets, making it the ultimate fusion of style and functionality.", image: "/assets/hoodies/hoodie-2.jpeg", name: "Black Hoodie.", price: "49.99" },
      { id: 11, description: "Introducing the CityFlex Hoodie, where cutting-edge technology meets streetwear flair. This hoodie boasts a tech-inspired design with hidden pockets for your gadgets, making it the ultimate fusion of style and functionality.", image: "/assets/hoodies/hoodie-3.jpeg", name: "Green Hoodie.", price: "49.99" },
      { id: 12, description: "Introducing the CityFlex Hoodie, where cutting-edge technology meets streetwear flair. This hoodie boasts a tech-inspired design with hidden pockets for your gadgets, making it the ultimate fusion of style and functionality.", image: "/assets/hoodies/hoodie-4.jpeg", name: "Cream Hoodie.", price: "49.99" },
    ],
    sweatshirts: [
      { id: 13, description: "Wrap yourself in CityWarmth, the epitome of cozy street elegance. This sweatshirt, with its plush fabric and relaxed fit, offers the warmth you need without compromising style. The minimalist branding and attention to detail make it a versatile addition to your streetwear collection.", image: "/assets/sweatshirts/sweatshirt-1.jpeg", name: "Green Sweatshirt.", price: "49.99" },
      { id: 14, description: "Wrap yourself in CityWarmth, the epitome of cozy street elegance. This sweatshirt, with its plush fabric and relaxed fit, offers the warmth you need without compromising style. The minimalist branding and attention to detail make it a versatile addition to your streetwear collection.", image: "/assets/sweatshirts/sweatshirt-2.jpeg", name: "White Sweatshirt.", price: "49.99" },
      { id: 15, description: "Wrap yourself in CityWarmth, the epitome of cozy street elegance. This sweatshirt, with its plush fabric and relaxed fit, offers the warmth you need without compromising style. The minimalist branding and attention to detail make it a versatile addition to your streetwear collection.", image: "/assets/sweatshirts/sweatshirt-3.jpeg", name: "Cream Sweatshirt.", price: "49.99" },
      { id: 16, description: "Wrap yourself in CityWarmth, the epitome of cozy street elegance. This sweatshirt, with its plush fabric and relaxed fit, offers the warmth you need without compromising style. The minimalist branding and attention to detail make it a versatile addition to your streetwear collection.", image: "/assets/sweatshirts/sweatshirt-4.jpeg", name: "Red Sweatshirt.", price: "49.99" },
    ],
    jackets: [
      { id: 17, description: "Meet your new favorite jeans - UrbanFlex Denim, designed for those who move with style. These jeans blend a classic denim look with a touch of street flair. The stretch fabric ensures flexibility and comfort, while the distressed details add an edge to your ensemble.", image: "/assets/jackets/jacket-1.jpeg", name: "Yellow Jacket.", price: "49.99" },
      { id: 18, description: "Meet your new favorite jeans - UrbanFlex Denim, designed for those who move with style. These jeans blend a classic denim look with a touch of street flair. The stretch fabric ensures flexibility and comfort, while the distressed details add an edge to your ensemble.", image: "/assets/jackets/jacket-2.jpeg", name: "Orange jacket.", price: "49.99" },
      { id: 19, description: "Meet your new favorite jeans - UrbanFlex Denim, designed for those who move with style. These jeans blend a classic denim look with a touch of street flair. The stretch fabric ensures flexibility and comfort, while the distressed details add an edge to your ensemble.", image: "/assets/jackets/jacket-3.jpeg", name: "Puffer Jacket.", price: "49.99" },
      { id: 20, description: "Meet your new favorite jeans - UrbanFlex Denim, designed for those who move with style. These jeans blend a classic denim look with a touch of street flair. The stretch fabric ensures flexibility and comfort, while the distressed details add an edge to your ensemble.", image: "/assets/jackets/jacket-4.jpeg", name: "Checkered Jacket.", price: "49.99" },
    ],
    sneakers: [
      { id: 21, description: "Step into the future with UrbanStride Sneakers, a bold statement in street footwear. The sleek design, coupled with high-performance features, makes these sneakers your go-to for urban exploration.", image: "/assets/sneakers/sneaker-1.jpg", name: "Colored Sneakers.", price: "49.99" },
      { id: 22, description: "Step into the future with UrbanStride Sneakers, a bold statement in street footwear. The sleek design, coupled with high-performance features, makes these sneakers your go-to for urban exploration.", image: "/assets/sneakers/sneaker-2.jpg", name: "Colored Sneakers.", price: "49.99" },
      { id: 23, description: "Step into the future with UrbanStride Sneakers, a bold statement in street footwear. The sleek design, coupled with high-performance features, makes these sneakers your go-to for urban exploration.", image: "/assets/sneakers/sneaker-3.jpg", name: "Colored Sneakers.", price: "49.99" },
      { id: 24, description: "Step into the future with UrbanStride Sneakers, a bold statement in street footwear. The sleek design, coupled with high-performance features, makes these sneakers your go-to for urban exploration.", image: "/assets/sneakers/sneaker-4.jpg", name: "Colored Sneakers.", price: "49.99" },
    ],
  };
  

export default productData